# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36e54fb525820934aaadd530e8491e15b63fc3519eca72fd7a80957a4ae76f1884cca92764fb5023ce196729256133ce2f0a011664ed174c04e8aef4da4bddc8

test:
  secret_key_base: 41af4ec001c2eba87cbdf9be24e94f7578d0e184ea1447e279afbc6e268ee579d4c3dca2cc8d37cf2f50583244f121996b958a1fe8f59231557e4697cbe83ed5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
